/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFreeChartForm;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Rosita_Nesya
 */
public class JFreeChartCSVDemo extends javax.swing.JFrame {

    /**
     * Creates new form JFreeChartCSVDemo
     */
    public JFreeChartCSVDemo() {
        initComponents();
        setTitle("JFreeChart with CSV Demo");
    }
    
    public void createPieChart() {
    try {
        // variable untuk pembacaan file csv
        BufferedReader br;
        String line = null;

        // menentukan range data untuk bar chart
        DefaultPieDataset my_pie_chart_dataset = new DefaultPieDataset();

        try {
            br = new BufferedReader(new
                    FileReader("src/JFreeChartForm/pieDataSet.csv"));

            while ((line = br.readLine()) != null) {
                String[] column = line.split(",");
                my_pie_chart_dataset.setValue(column[0],
                        Integer.parseInt(column[1]));
            }

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

        // metode ini mengembalikan objek JFreeChart
        JFreeChart myPieChart = ChartFactory.createPieChart(
                "Keyword Vs Count", my_pie_chart_dataset, true, true, true);

        // tampilkan ke layar
        int width = 640; // lebar gambar
        int height = 480; // tinggi gambar

        // menampilkan ke layar monitor
        ChartFrame chartFrame = new ChartFrame("Pie Chart Demo", myPieChart);
        chartFrame.setSize(width, height);
        chartFrame.setVisible(true);

    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
}
    
    public void createBarChart() {
    try {
        // variable untuk pembacaan file csv
        BufferedReader br;
        String line = null;

        // menentukan range data untuk bar chart
        DefaultCategoryDataset my_bar_chart_dataset =
                new DefaultCategoryDataset();

        try {
            br = new BufferedReader(new
                    FileReader("src/JFreeChartForm/barDataSet.csv")); // Must use absolute path
            //System.out.println(br);
            while ((line = br.readLine()) != null) {
                String[] column = line.split(",");
                my_bar_chart_dataset.addValue(Integer.parseInt(column[0]),
                        column[1], column[2]);
            }

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

        // metode ini mengembalikan objek JFreeChart
        JFreeChart myBarChart = ChartFactory.createBarChart(
                "Keyword Vs Count", "Keyword", "Count", my_bar_chart_dataset,
                PlotOrientation.VERTICAL, true, true, true);

        // tampilkan ke layar
        int width = 640; // lebar gambar
        int height = 480; // tinggi gambar

        // menampilkan ke layar monitor
        ChartFrame chartFrame = new ChartFrame("Bar Chart Demo", myBarChart);
        chartFrame.setSize(width, height);
        chartFrame.setVisible(true);

    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Bar Chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pie Chart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int a = JOptionPane.showConfirmDialog(null, "Keluar dari aplikasi?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(a == JOptionPane.YES_OPTION)this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
createBarChart();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
createPieChart();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFreeChartCSVDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFreeChartCSVDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFreeChartCSVDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFreeChartCSVDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFreeChartCSVDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
