/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFreeChartForm;


 import com.lowagie.text.Document;
import com.lowagie.text.Image;
import com.lowagie.text.pdf.DefaultFontMapper;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfTemplate;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
//import javax.swing.text.Document;

//import org.jsoup.nodes.Document; import org.jsoup.Jsoup; 

/**
 *
 * @author Rosita_Nesya
 */
public class JFreeChartToPDF extends javax.swing.JFrame {

    /**
     * Creates new form JFreeChartToPDF
     */
    public JFreeChartToPDF() {
        initComponents();
        setTitle("JFreeChart to PDF Demo");
    }

    public void writeChartToPDF(JFreeChart chart, int width, int height,
            String fileName) {

        PdfWriter writer = null;

        Document document = new Document();

        try {
            writer = PdfWriter.getInstance(document, new FileOutputStream(
                    fileName));

            document.open();

            PdfContentByte contentByte = writer.getDirectContent();
            PdfTemplate template
                    = contentByte.createTemplate(width, height);

            Graphics2D graphics2d = template.createGraphics(width, height,
                    new DefaultFontMapper());

            Rectangle2D rectangle2d = new Rectangle2D.Double(0, 0, width, height);
            chart.draw(graphics2d, rectangle2d);

            graphics2d.dispose();
            Image img = Image.getInstance(template);

            document.add(img);

        } catch (Exception e) {
            System.out.println("Terjadi error membuat PDF!");

        }
        document.close();

    }

    // menentukan range data untuk bar chart
    public JFreeChart createBarChart() {
        DefaultCategoryDataset my_bar_chart_dataset
                = new DefaultCategoryDataset();

        my_bar_chart_dataset.addValue(77, "Keyword", "JFreeChart");
        my_bar_chart_dataset.addValue(80, "Keyword", "Batik");

        my_bar_chart_dataset.addValue(55, "Keyword", "Chart");
        my_bar_chart_dataset.addValue(67, "Keyword", "Apache");

        my_bar_chart_dataset.addValue(80, "Keyword", "Java");

        // metode ini mengembalikan objek JFreeChart
        JFreeChart myBarChart = ChartFactory.createBarChart(
                "Keyword Vs Count", "Keyword", "Count", my_bar_chart_dataset,
                PlotOrientation.VERTICAL, true, true, true);

        // membuat grafik chart di jpanel
        panelChart.removeAll();
        ChartPanel chartPanel = new ChartPanel(myBarChart);

        chartPanel.setSize(400, 300);
        panelChart.setSize(400, 300);

        panelChart.add(chartPanel);
        panelChart.repaint();

        return myBarChart;
    }
    public JFreeChart createPieChart() {
        // menentukan range data untuk bar chart
        DefaultPieDataset my_pie_chart_dataset =
                new DefaultPieDataset();

        my_pie_chart_dataset.setValue("JFreeChart", 77);
        my_pie_chart_dataset.setValue("Batik", 80);
        my_pie_chart_dataset.setValue("Chart", 55);
        my_pie_chart_dataset.setValue("Apache", 67);
        my_pie_chart_dataset.setValue("Java", 80);

        // metode ini mengembalikan objek JFreeChart
        JFreeChart myPieChart = ChartFactory.createPieChart(
                "Keyword Vs Count", my_pie_chart_dataset, true, true, true);

        // membuat grafik chart di jpanel
        panelChart.removeAll();
        ChartPanel chartPanel = new ChartPanel(myPieChart);

        chartPanel.setSize(400, 300);
        panelChart.setSize(400, 300);

        panelChart.add(chartPanel);
        panelChart.repaint();

        return myPieChart;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBarChart = new javax.swing.JButton();
        btnPieChart = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnSaveAsPDF = new javax.swing.JButton();
        panelChart = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBarChart.setText("Bar Chart");
        btnBarChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarChartActionPerformed(evt);
            }
        });

        btnPieChart.setText("Pie Chart");
        btnPieChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPieChartActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnSaveAsPDF.setText("Save as PDF");
        btnSaveAsPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAsPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelChartLayout = new javax.swing.GroupLayout(panelChart);
        panelChart.setLayout(panelChartLayout);
        panelChartLayout.setHorizontalGroup(
            panelChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelChartLayout.setVerticalGroup(
            panelChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBarChart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPieChart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveAsPDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(btnKeluar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBarChart)
                    .addComponent(btnPieChart)
                    .addComponent(btnKeluar)
                    .addComponent(btnSaveAsPDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
int a = JOptionPane.showConfirmDialog(null, "Keluar dari aplikasi?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(a == JOptionPane.YES_OPTION)this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnBarChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarChartActionPerformed
createBarChart();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBarChartActionPerformed

    private void btnPieChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPieChartActionPerformed
createPieChart();        // TODO add your handling code here:
    }//GEN-LAST:event_btnPieChartActionPerformed

    private void btnSaveAsPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAsPDFActionPerformed
writeChartToPDF(createBarChart(), 500, 400, "src/JFreeChart/BarChart.pdf");
writeChartToPDF(createPieChart(), 500, 400, "src/JFreeChart/PieChart.pdf");

System.out.println("Bar Chart dan Pie Chart berhasil disimpan!");        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveAsPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFreeChartToPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFreeChartToPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFreeChartToPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFreeChartToPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFreeChartToPDF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarChart;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPieChart;
    private javax.swing.JButton btnSaveAsPDF;
    private javax.swing.JPanel panelChart;
    // End of variables declaration//GEN-END:variables
}
