/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package STMIK;

import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import javax.swing.table.TableColumn;
/**
 *
 * @author Rosita_Nesya
 */
public class MahasiswaFormDB extends javax.swing.JFrame {

    MahasiswaModelDB model = new MahasiswaModelDB();

    /** Creates new form MahasiswaForm */
    public MahasiswaFormDB() {
        initComponents();

        setTitle("Form Mahasiswa");

        // mengisi data-data pada combo box jurusan
        isiComboBox();

        // mengosongkan isian data
        kosongkanIsian();

        // mengambil pengaturan kolom dari model
        tabelMahasiswa.setModel(model);

        // mengatur lebar untuk masing-masing kolom tabel
        setKolomTabel();

        // panggil tampilData();
        tampilData();
    }

    public void isiComboBox() {
        // menghapus semua data pada combo box
        cboJurusan.removeAllItems();

        // menambahkan data-data jurusan pada combo box
        cboJurusan.addItem("SI");
        cboJurusan.addItem("KA");
    }

    public void kosongkanIsian() {
        // mengatur isian text field menjadi kosong
        txtNIM.setText("");
        txtNama.setText("");
        txtTmpLahir.setText("");

        // mengatur chooser date menjadi kosong
        calTglLahir.setDate(null);

        // mengatur combo box memilih index 0
        cboJurusan.setSelectedIndex(0);
    }

    public void setKolomTabel() {
        // mengatur lebar kolom untuk masing-masing kolom
        TableColumn column = null;
        for (int i = 0; i < 5; i++) {
            column = tabelMahasiswa.getColumnModel().getColumn(i);
            switch (i) {
                case 0:
                    column.setPreferredWidth(60);
                    break;
                case 1:
                    column.setPreferredWidth(100);
                    break;
                case 2:
                    column.setPreferredWidth(100);
                    break;
                case 3:
                    column.setPreferredWidth(80);
                    break;
                case 4:
                    column.setPreferredWidth(20);
                    break;
            }
        }
    }
    
    public void tampilData() {
        // melakukan koneksi ke database dan tabel via KoneksiDB
        try {
            Connection c = KoneksiDB.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tbMahasiswa";
            ResultSet rs = s.executeQuery(sql);

            while (rs.next()) {
                // lakukan penelusuran baris
                Object[] o = new Object[5];
                o[0] = rs.getString("nim");
                o[1] = rs.getString("nama");
                o[2] = rs.getString("tmpLahir");
                o[3] = rs.getString("tglLahir");
                o[4] = rs.getString("jurusan");

                model.addRow(Arrays.asList(o));
            }
        } catch (SQLException e) {
            System.out.println("Terjadi error menampilkan data di tabel!");
        }
    }

    private java.sql.Date konversiDate(java.util.Date utilDate) {
        java.sql.Date sqlDate = null;
        if (utilDate != null) {
            sqlDate = new java.sql.Date(utilDate.getTime());
        }
        return sqlDate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTmpLahir = new javax.swing.JTextField();
        calTglLahir = new com.toedter.calendar.JDateChooser();
        cboJurusan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        jLabel3.setText("Tempat Lahir");

        jLabel4.setText("Tanggal Lahir");

        jLabel5.setText("Jurusan");

        txtNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIMActionPerformed(evt);
            }
        });

        cboJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Keluar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMahasiswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTmpLahir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calTglLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNIM, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtNama))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTmpLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(calTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int a = JOptionPane.showConfirmDialog(null, "Keluar dari aplikasi?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(a == JOptionPane.YES_OPTION)this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nim = txtNIM.getText();
String nama = txtNama.getText();
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

// jika tanggal lahir belum dipilih maka return
if (calTglLahir.getDate() == null) {
    return;
}

String tglLahir = sdf.format(calTglLahir.getDate());
String tmpLahir = txtTmpLahir.getText();
String jurusan = cboJurusan.getSelectedItem().toString();

// memasukkan data yang diinputkan ke database
try {
    Connection c = KoneksiDB.getKoneksi();
    String sql = "INSERT INTO tbMahasiswa VALUES (?, ?, ?, ?, ?)";
    PreparedStatement p = c.prepareStatement(sql);

    p.setString(1, nim);
    p.setString(2, nama);
    p.setString(3, tmpLahir);
    p.setDate(4, konversiDate(calTglLahir.getDate()));
    p.setString(5, jurusan);

    p.executeUpdate();
    p.close();

} catch (SQLException e) {
    System.out.println("Terjadi error menambah data di database");
}

// memasukkan data yang diinputkan ke dalam model
model.addRow(Arrays.asList(nim, nama, tmpLahir, tglLahir, jurusan));

// perbaharui tampilan jtable
tabelMahasiswa.setModel(model);

// mengatur kolom tabel
setKolomTabel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 // TODO add your handling code here:

    // mengambil index dari baris yang dipilih/diseleksi
    int index = tabelMahasiswa.getSelectedRow();

    // jika tidak ada baris terseleksi maka return
    if (index == -1) {
        return;
    }

    // mengambil nilai-nilai isian pada form
    // nim, nama, tmplahir, tgllahir, jurusan
    String nim = txtNIM.getText();
    String nama = txtNama.getText();
    String tmpLahir = txtTmpLahir.getText();

    // jika date chooser belum diisi maka return
    if (calTglLahir.getDate() == null) {
        return;
    }

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String tglLahir = sdf.format(calTglLahir.getDate());
    String jurusan = cboJurusan.getSelectedItem().toString();

    // memasukkan data yang diedit ke dalam database
    try {
        Connection c = KoneksiDB.getKoneksi();
        String sql = "UPDATE tbMahasiswa SET nama=?, tmpLahir=?, tglLahir=?, jurusan=? WHERE nim=?"; // Corrected SQL query
        PreparedStatement p = c.prepareStatement(sql);
        p.setString(1, nama);
        p.setString(2, tmpLahir);
        p.setDate(3, konversiDate(calTglLahir.getDate()));
        p.setString(4, jurusan);
        p.setString(5, nim); // Corrected parameter index to 5

        p.executeUpdate();
        p.close();

    } catch (SQLException e) {
        System.out.println("Terjadi error mengubah data dalam database!");
    } finally {
        // memasukkan data yang diedit ke dalam model
        model.setValueAt(nim, index, 0);
        model.setValueAt(nama, index, 1);
        model.setValueAt(tmpLahir, index, 2);
        model.setValueAt(tglLahir, index, 3);
        model.setValueAt(jurusan, index, 4);

        // perbaharui tampilan jtable
        tabelMahasiswa.setModel(model);

        // mengatur kolom tabel
        setKolomTabel();

    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int index = tabelMahasiswa.getSelectedRow();

// jika tidak ada baris terseleksi maka return
if (index == -1) {
    return;
}

// ambil yang terseleksi
String nim = (String) model.getValueAt(index, 0);

// menghapus data di database
try {
    Connection c = KoneksiDB.getKoneksi();
    String sql = "DELETE FROM tbMahasiswa WHERE nim = ?";
    PreparedStatement p = c.prepareStatement(sql);

    p.setString(1, nim);

    p.executeUpdate();
    p.close();

} catch (SQLException e) {
    System.out.println("Terjadi Error menghapus data!");

} finally {
    // menghapus baris di model tabel
    model.removeRow(index);
    // perbaharui tampilan jtable
    tabelMahasiswa.setModel(model);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMahasiswaMouseClicked
        // TODO add your handling code here:
        int index = tabelMahasiswa.getSelectedRow();

// jika tidak ada baris terseleksi maka return
if (index == -1) {
    return;
}

// membuat variable (nim, nama, tmpLahir, tglLahir, jurusan) untuk
// menampung data berdasarkan baris yang dipilih/diseleksi
String nim = (String) tabelMahasiswa.getValueAt(index, 0);
String nama = (String) tabelMahasiswa.getValueAt(index, 1);
String tmpLahir = (String) tabelMahasiswa.getValueAt(index, 2);
String tglLahir = (String) tabelMahasiswa.getValueAt(index, 3);
String jurusan = (String) tabelMahasiswa.getValueAt(index, 4);

// menampilkan variabel-variabel yang dipilih ke text field
txtNIM.setText(nim);
txtNama.setText(nama);
txtTmpLahir.setText(tmpLahir);

// jika tanggal lahir kosong maka return
if (tglLahir.isEmpty()) {
    return;
}

// menampilkan variabel tglLahir ke calTglLahir
try {
    java.util.Date tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(tglLahir);
    calTglLahir.setDate(tanggal);
} catch (Exception e) {
    System.out.println("Terjadi error menampilkan tanggal");
}

// menampilkan variabel-variable yang dipilih ke combo box
if (jurusan.equals("SI")) {
    cboJurusan.setSelectedIndex(0);
} else {
    cboJurusan.setSelectedIndex(1);
}
    }//GEN-LAST:event_tabelMahasiswaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MahasiswaFormDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MahasiswaFormDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MahasiswaFormDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MahasiswaFormDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MahasiswaFormDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calTglLahir;
    private javax.swing.JComboBox<String> cboJurusan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMahasiswa;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTmpLahir;
    // End of variables declaration//GEN-END:variables
}
