/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JTableKtnyLanjutan;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Rosita_Nesya
 */
public class MahasiswaView extends javax.swing.JFrame {

    MahasiswaModel model = new MahasiswaModel();

/* Creates new form KRSTable */
public MahasiswaView() {
    initComponents();

    setTitle("View data Mahasiswa");
    tabelMahasiswa.setModel(model);
}

public JTable getTabelMahasiswa() {
    return tabelMahasiswa;
}

public MahasiswaModel getTabelModel() {
    return model;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelMahasiswa);

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Keluar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int a = JOptionPane.showConfirmDialog(null, "Keluar dari aplikasi?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(a == JOptionPane.YES_OPTION)this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
MahasiswaEditor mhsEditor = new MahasiswaEditor(this, true);
// menonaktifkan tombol Edit
mhsEditor.getButtonTambah().setEnabled(true);
mhsEditor.getButtonUbah().setEnabled(false);
mhsEditor.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                         
        // TODO add your handling code here:
        MahasiswaEditor mhsEditor = new MahasiswaEditor(this, true);

        // menonaktifkan tombol Edit
        mhsEditor.getButtonTambah().setEnabled(false);
        mhsEditor.getButtonUbah().setEnabled(true);

        // mengambil index dari baris yang dipilih/diseleksi
        int index = tabelMahasiswa.getSelectedRow();

        // jika tidak ada baris terseleksi maka return
        if (index == -1) {
            return;
        }

        // membuat variable (nama, jurusan, umur, jenis kelamin) untuk
        // menampung data berdasarkan baris yang dipilih/diseleksi
        String nama = (String) tabelMahasiswa.getValueAt(index, 0);
        String jurusan = (String) tabelMahasiswa.getValueAt(index, 1);
        String tglLahir = (String) tabelMahasiswa.getValueAt(index, 2);
        String tmpLahir = (String) tabelMahasiswa.getValueAt(index, 3);
        String jenisKelamin = (String) tabelMahasiswa.getValueAt(index, 4);

        // menampilkan variable-variable yang dipilih ke text field
        mhsEditor.getTextFieldNama().setText(nama);
        //mhsEditor.getDateChooserTglLahir().get
        mhsEditor.getTextFieldTmpLahir().setText(tmpLahir);

        // menampilkan variabel-variable yang dipilih ke combo box
        if (jurusan.equals("Komputerisasi Akuntansi")) {
            mhsEditor.getComboBoxJurusan().setSelectedIndex(0);
        } else {
            mhsEditor.getComboBoxJurusan().setSelectedIndex(1);
        }
        if (jenisKelamin.equals("Pria")) {
            mhsEditor.getComboBoxJenisKelamin().setSelectedIndex(0);
        } else {
            mhsEditor.getComboBoxJenisKelamin().setSelectedIndex(1);
        }

        // jika tanggal lahir kosong maka return
        if (tglLahir.isEmpty()) {
            return;
        }

        // menampilkan variabel yang dipilih ke date chooser
        try {
            java.util.Date tanggal = new SimpleDateFormat("dd-MM-yyyy").parse(tglLahir);
            mhsEditor.getDateChooserTglLahir().setDate(tanggal);
        } catch (Exception e) {
            System.out.println("Terjadi error menampilkan tanggal");
        }

        mhsEditor.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int index = tabelMahasiswa.getSelectedRow();

// jika tidak ada baris terseleksi maka return
if (index == -1) {
    return;
} else {
    // lakukan operasi hapus data berdasarkan index
    model.removeRow(index);
}

// perbaharui tampilan jtable
tabelMahasiswa.setModel(model);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MahasiswaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMahasiswa;
    // End of variables declaration//GEN-END:variables
}
