/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package JTableKtnyLanjutan;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import javax.swing.*;
import javax.swing.table.TableColumn;
//import javax.swing.JButton;
/**
 *
 * @author Rosita_Nesya
 */
public class MahasiswaEditor extends javax.swing.JDialog {

    MahasiswaView mhsView;

/** Creates new form MahasiswaEditor */
public MahasiswaEditor(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    mhsView = (MahasiswaView) parent;
    initComponents();

    setTitle("Editor data Mahasiswa");
    setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    // isi data untuk masing-masing combobox
    isiComboBox();

    // menghapus isian
    kosongkanIsian();
}

private void isiComboBox() {
    // isi nilai-nilai untuk combo box jurusan
    cboJurusan.removeAllItems();
    cboJurusan.addItem("Komputerisasi Akuntansi");
    cboJurusan.addItem("Sistem Informasi");

    // isi nilai-nilai untuk combo box jenis kelamin
    cboJenisKelamin.removeAllItems();
    cboJenisKelamin.addItem("Pria");
    cboJenisKelamin.addItem("Wanita");
}

private void kosongkanIsian() {
    // menghapus isian dan mengatur seleksi ke default
    txtNama.setText("");
    cboJurusan.setSelectedIndex(0);
    calTglLahir.setCalendar(null);
    txtTmpLahir.setText("");
    cboJenisKelamin.setSelectedIndex(0);
}

public void setKolomTabel() {
    // mengatur lebar kolom untuk masing-masing kolom
    TableColumn column = null;
    for (int i = 0; i < 5; i++) { // Corrected loop condition to i < 5
        column = mhsView.getTabelMahasiswa().getColumnModel().getColumn(i);
        switch (i) {
            case 0:
                column.setPreferredWidth(80);
                break;
            case 1:
                column.setPreferredWidth(100);
                break;
            case 2:
                column.setPreferredWidth(50);
                break;
            case 3:
                column.setPreferredWidth(80);
                break;
            case 4:
                column.setPreferredWidth(20);
                break;
        }
    }
}

public JButton getButtonTambah() {
    return btnTambah;
}

public JButton getButtonUbah() {
    return btnUbah; // Corrected typo "bunübah" to "btnUbah"
}

public JTextField getTextFieldNama() {
    return txtNama;
}

public JComboBox getComboBoxJurusan() {
    return cboJurusan;
}

public JDateChooser getDateChooserTglLahir() {
    return calTglLahir;
}

public JTextField getTextFieldTmpLahir() {
    return txtTmpLahir;
}

public JComboBox getComboBoxJenisKelamin() {
    return cboJenisKelamin;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        cboJurusan = new javax.swing.JComboBox<>();
        calTglLahir = new com.toedter.calendar.JDateChooser();
        txtTmpLahir = new javax.swing.JTextField();
        cboJenisKelamin = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Jurusan");

        jLabel3.setText("Tanggal Lahir");

        jLabel4.setText("Tempat Lahir");

        jLabel5.setText("Jenis Kelamin");

        cboJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(btnBatal))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTmpLahir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama)
                                    .addComponent(cboJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(calTglLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(calTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtTmpLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cboJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnBatal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
String nama = txtNama.getText();
String jurusan = cboJurusan.getSelectedItem().toString();
SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

// jika tanggal lahir belum dipilih maka return
if (calTglLahir.getDate() == null) {
    return;
}

String tglLahir = sdf.format(calTglLahir.getDate());
String tmpLahir = txtTmpLahir.getText();
String jenisKelamin = cboJenisKelamin.getSelectedItem().toString();

// memasukkan data yang diinputkan ke dalam model
mhsView.getTabelModel().addRow(Arrays.asList(nama, jurusan,
        tglLahir, tmpLahir, jenisKelamin));

// perbaharui tampilan jtable
mhsView.getTabelMahasiswa().setModel(mhsView.getTabelModel());

// mengatur kolom tabel
setKolomTabel();

// kembali ke form MahasiswaView
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
String nama = txtNama.getText();
String jurusan = cboJurusan.getSelectedItem().toString();
SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
String tglLahir = sdf.format(calTglLahir.getDate());
String tmpLahir = txtTmpLahir.getText();
String jenisKelamin = cboJenisKelamin.getSelectedItem().toString();

// mengambil index dari baris yang dipilih/diseleksi
int index = mhsView.getTabelMahasiswa().getSelectedRow();

// jika tidak ada baris terseleksi maka return
if (index == -1) {
    return;
} else {
    // memasukkan data yang diedit ke dalam model
    mhsView.getTabelModel().setValueAt(nama, index, 0);
    mhsView.getTabelModel().setValueAt(jurusan, index, 1);
    mhsView.getTabelModel().setValueAt(tglLahir, index, 2);
    mhsView.getTabelModel().setValueAt(tmpLahir, index, 3);
    mhsView.getTabelModel().setValueAt(jenisKelamin, index, 4);
}

// perbaharui tampilan jtable
mhsView.getTabelMahasiswa().setModel(mhsView.getTabelModel());

// mengatur kolom tabel
setKolomTabel();

dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
int a = JOptionPane.showConfirmDialog(null, "Keluar dari aplikasi?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(a == JOptionPane.YES_OPTION)this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MahasiswaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MahasiswaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MahasiswaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MahasiswaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MahasiswaEditor dialog = new MahasiswaEditor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private com.toedter.calendar.JDateChooser calTglLahir;
    private javax.swing.JComboBox<String> cboJenisKelamin;
    private javax.swing.JComboBox<String> cboJurusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTmpLahir;
    // End of variables declaration//GEN-END:variables
}
